name: 'Petitions polling'
on:
  push:
    tags: [ "run-once" ]
  schedule:
    - cron: "3 * * * *"

jobs:

  poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: make fetch
      - run: make update
